### ISSUE TITLE
Question - Acrobat Reader : unsupported algorithm 

### ISSUE THREAD

**Issue by kmillet** [Fedict/eid-mw#172] opened 2022-06-29 09:39 UTC
While trying to use the eid middleware on Mac (Big Sur) I experience the same issue as described on https://community.adobe.com/t5/acrobat-reader-discussions/niet-ondersteund-algoritme-unsupported-algoritme/m-p/12635530.
The adobe support team on that forum points to the issuing authority of the signature profile.

I wonder now what is causing this issue? Based on that forum, it seems to work on Windows by just not using the pkcs#11 module. However, in Mac there doesn't seem to be another option. Any ideas on how to solve it?

**Comment by MatthiasValvekens** [comment] 2022-06-29 10:47
Possibly Acrobat doesn't support ECDSA signing using generic PKCS#11 modules. I know they support validation (for NIST curves, at least), but I never bothered to test signing.

If you're not afraid of some CLI and/or Python experimentation, you could try signing with [this tool of mine](https://github.com/MatthiasValvekens/pyHanko). I never tested ECDSA with eID cards (mine is still an old one), but a couple months ago I did do some testing with ECDSA against a YubiKey over PKCS#11, and that worked fine. If you can sign using pyHanko then the problem is almost certainly on Acrobat's end.

Maybe I should try using my YubiKey to produce some ECDSA signatures in Acrobat at some point...

**Comment by MatthiasValvekens** [comment] 2022-06-29 12:35
Yeah, Adobe has historically been pretty slow about adopting new cryptographic standards. You could try raising an issue on their [UserVoice](https://acrobat.uservoice.com/) platform, but be aware that it's mostly a black hole.

There's an [extension](https://www.iso.org/standard/45875.html) to the PDF spec in the final stages of the ISO process that clarifies some things related to ECDSA support (among other things). Hopefully that'll give a boost to adoption to the point that Adobe actually starts caring, but who knows...

Anyway, I think we've established that the problem is not in the middleware. That's already something :).

**Comment by Frederikus** [comment] 2022-06-30 08:13
Does the solution/workaround that is presented in your link https://community.adobe.com/t5/acrobat-reader-discussions/niet-ondersteund-algoritme-unsupported-algoritme/m-p/12635530.  work for you?
Basically it means removing the link to the pkcs#11 module from within Acrobat.
Then you are sure that Acrobat will use the BEIDToken to access the eID card and not go via pkcs#11

**Comment by Frederikus** [comment] 2022-06-30 09:21
That solution is specifically for macOS. In the past, Acrobat didn't worked with the apple frameworks to communicate with the eID card, but the current Acrobat versions do.

**Comment by Frederikus** [comment] 2022-06-30 11:46
It should work with any CCID card reader. I just retested here on a mac mini, M1 and signing goes fine.
When you open Apple's "System Information" app. (in /Applications/Utilities), do you see your cards certificates? (in Software -> Smart Cards) They should be shown in a keychain name "be.fedict.BEIDTokenApp.BEIDToken,....."

If they are there, then the eID middleware is operational and the certificates are present. (note that they are no longer visible under Keychain Access since Apple introduced the CTK framework).

I'm informed that you already checked with the service desk, could you post your findings there, then we'll continue there?

**Comment by Frederikus** [comment] 2022-09-29 11:56
closing this, 
should anyone have further info or a similar issue, feel free to re-open

**Closed by Frederikus** 2022-09-29 11:56 UTC
